stages:
  - build

cmake:
  stage: build
  image: rootproject/root-ubuntu16
  script:
    - sudo apt-get update
    - sudo apt-get upgrade -y
    - sudo apt-get install -y ninja-build git
    - git submodule update --init --recursive
    - mkdir -p tmva-branch-adder-build
    - mkdir -p tmva-branch-adder-install
    - cmake -Htmva-branch-adder-source -Btmva-branch-adder-build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=tmva-branch-adder-install -DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
    - cmake --build tmva-branch-adder-build --target install
    - cd $(mktemp -d)
    - cmake ${CI_PROJECT_DIR} -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$(mktemp -d) -DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_PREFIX_PATH=${CI_PROJECT_DIR}/tmva-branch-adder-install/share
    - cmake --build .
